version: "3"

services:
    nexus:
        image: sonatype/nexus3:latest
        ports:
            - "8081:8081"
            - "8123:8123"
        volumes:
            - ${LOCAL_PATH_NEXUS_DATA}/nexus:/nexus-data
        restart: always
