version: '3.5'

services:

  postgres:
    image: postgres
    container_name: "${POSTGRES_CONTAINER_NAME}"
    restart: always
    ports: 
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${POSTGRES_DATA}:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  pgadmin:
    image: dpage/pgadmin4
    container_name: "${PGADMIN_CONTAINER_NAME}"
    restart: always
    ports:
      - "${PGADMIN_PORT}:8080"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"