version: "3"
services:
 rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    volumes:
      - '${LOCAL_PATH_RABBITMQ_DATA}:/data'

volumes:
  rabbitmq_data: